version: 2
jobs:
  build:
    working_directory: ~/kafka-php
    docker:
      - image: videoblocks/docker-php
      - image: redis:2.8
      - image: confluentinc/cp-zookeeper:5.1.2
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
      - image: confluentinc/cp-enterprise-kafka:5.1.2
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: 'localhost:2181'
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      - image: confluentinc/cp-schema-registry:5.1.2
        environment:
          SCHEMA_REGISTRY_HOST_NAME: localhost
          SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'localhost:2181'
      - image: redis:2.8

    steps:
      - checkout

      - restore_cache:
          keys:
            - vendor-v1-{{ checksum "composer.lock" }}
            - vendor-v1-

      - run: composer config -g github-oauth.github.com $GIT_ACCESS_TOKEN

      - run: composer install

      - save_cache:
          paths:
            - vendor
          key: vendor-v1-{{ checksum "composer.lock" }}

      - run:
          name: Wait for schema registry.
          command: |
            printf "Waiting for schema registry"
            until curl -s 0.0.0.0:8081 > /dev/null; do printf "."; sleep 1; done

      - run: cp .env.example .env

      - run: vendor/bin/phpunit --log-junit test-reports/junit.xml --testdox

      - store_test_results:
          path: test-reports
